### PR TITLE
Better error messages for opening repos.

### LINKED ISSUE #645: error on non-existent Git repository is very non-specific
When I try to open a `Repository` using a path that doesn't actually contain a Git repo, the error is a very non-specific `KeyError`:

``` python
>>> print(pygit2.__version__)
0.24.1
>>> os.mkdir('/tmp/foobarbaz')
>>> gitrepo=pygit2.Repository('/tmp/foobarbaz')
Traceback (most recent call last):

  File "<ipython-input-30-782283f588bb>", line 1, in <module>
    gitrepo=pygit2.Repository('/tmp/foobarbaz')

  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 64, in __init__
    super(Repository, self).__init__(path, *args, **kwargs)

KeyError: '/tmp/foobarbaz'
```

It would be helpful to replace this with a more specific `GitError`, so that the error from Git can be distinguished from a "normal" `KeyError` in a statement like this:

``` python
>>> repos = { "repo1":"/path/to/repo1", "repo2":"/path/to/repo2" }
>>> gitrepo = pygit2.Repository( repos["repo3"] )
```

### PR DESCRIPTION
**Pull request by tmr232**
Closes #645.

### CODE REVIEW

**Comment by tmr232** [comment]
@jdavid Seems like the same tests fail for every change I submit. Is it something wrong with the tests or the code?

File: src/pygit2.c [hunk 1]
```diff
@@ -151,29 +151,35 @@ PyDoc_STRVAR(init_file_backend__doc__,
...
+  }
+
+  if (err == GIT_ENOTFOUND) {
+    PyErr_Format(PyExc_Exception,
+            "Repository not found at %s", path);
+  } else {
+    PyErr_Format(PyExc_Exception,
+            "Git error %d while opening repo at %s", err, path);
+  }
+
```
Comment (jdavid) [inline src/pygit2.c]: Thanks, looks good. While you are at it, maybe change style to use 4 spaces indentation. Also, ``Exception`` is too generic, we should use a more specific exception; though choosing a good one is not easy.

Comment (tmr232) [inline src/pygit2.c]: Isn't there a `GitError` exception we can use?
And, do we have a style guide? I saw #238, but since it's open sinse 2013 I didn't really know what to make of it.

Comment (tmr232) [inline src/pygit2.c]: Oh, I just realized we have different indentation inside the same function... Fixing that now.

Comment (jdavid) [inline src/pygit2.c]: To make it simple: PEP 7 for C, PEP 8 for Python.

Comment (jdavid) [inline src/pygit2.c]: Just pushed a commit to raise GitError for GIT_ENOTFOUND (and to not change the error set by Error_set_str for the other cases, to avoid hiding information).

**Comment by jdavid** [comment]
It should be good for the tests now
